---

- hosts: all
  become: true
  tasks:
  - name: update repository index
    apt:
      update_cache: yes
    changed_when: false
  - name: install apache2 pacakage
    apt:
      name: apache2
      state: latest
  - name: install php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
  - name: copy default html files for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
- hosts: workstations
  become: true
  tasks:
  - name: install unzip
    package:
      name: unzip
  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


- hosts: all
  become: true
  tasks:


  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMefue09OOmiIykdvbt/M5Hx0QC2STHkXtVaYwwcrT87 ansible"


