- name: update repository index
  apt:
    update_cache: yes
  changed_when: false
- name: install apache and php
  tags: apache,php
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"

- name: copy default html files for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
